### ISSUE TITLE
Binary compatibility for null via tasty

### ISSUE THREAD

**Issue by abeln** [abeln/dotty#17]
This is trying to solve the following issue:

1) library A is compiled with dotty pre null change
2) program P uses library A via tasty (for typechecking) and is compiled with dotty post null change
3) library A defines
```
def foo(): String = ???
```
4) P should interpret `foo` as having a nullable return type

We'd like to re-use the Java null transform when loading `A` from tasty: https://github.com/abeln/dotty/blob/explicit-null/compiler/src/dotty/tools/dotc/core/JavaNull.scala

cc @olhotak

**Comment by olhotak** [comment]
I agree with the overall strategy.

**Comment by abeln** [comment]
This plan is dead. Long live the new plan: https://gist.github.com/abeln/9f79774bac111d99b3ae2cb9016a33e6#binary-compatibility
