### ISSUE TITLE
subclassing outside of Scala

### ISSUE THREAD

**Issue by dsilvasc** [abeln/dotty#9]
What would happen if a Scala trait defines a method that returns a non-nullable type, then someone provides an implementation in another language (like Java) that returns null?

Scala:

```scala
trait Demo {
  def m: String
}
```

Java:

```java
public class JavaImpl {
  public static Demo demo() {
    return new Demo() {
      @Override String m() { return null; }
    }
  }
}
```

Scala again:

```scala
val d: Demo = JavaImpl.demo
val str = d.m
println(str.length)  // compile error or runtime null pointer exception?
```

**Comment by abeln** [comment]
There's very little we can do in this kind of situation, unfortunately. This will likely remain as allowed but unsound (NPE at runtime).
